import _defaultUserImage from "../images/defaultUser.png";
import _exampleImg from "../images/exampleImg.png";

export const defaultUserImage = _defaultUserImage;
export const exampleImage = _exampleImg;
export const DUMMY_JWT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiZW1haWwiOiJtcnJ5dTAwNkBuYXZlci5jb20iLCJpZCI6IjYzMDQyODcyODY4NzUyMDAyZjllNjBlYyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsIm5hbWUiOiLsnKDsg4HsmrAiLCJ1c2VybmFtZSI6Im1ycnl1MDA2IiwiYmlydGhEYXRlIjpudWxsLCJwaG9uZU51bWJlciI6IjAxMDAwMDAwMDAwIn0sImdyb3VwIjoidm1lZXRpbmciLCJ0ZW5hbnQiOiJ0cmlhbCIsInNpdGVOYW1lIjoiVHJpYWwiLCJ0diI6IjMifSwicm9vbSI6IioiLCJpYXQiOjE2NjMzMDMxNzAsImV4cCI6MTY2MzkwNzk3MCwiYXVkIjoidm1lZXRpbmciLCJpc3MiOiJ2bWVldGluZ19hcHBfaWQiLCJzdWIiOiIqIn0.jiXXxcTKfmhAytT3tslmhHSaDn8G2UU6hlCdGSaZgkw";
