import _defaultUserImage from "../images/defaultUser.png";

export const defaultUserImage = _defaultUserImage;
export const DUMMY_JWT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiZW1haWwiOiJqdXN0aWNlZG9uZ0BuYXZlci5jb20iLCJpZCI6IjYzMDMyNGMzODY4NzUyMDAyZjllNjBlMiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsIm5hbWUiOiLsoJXsnZjrj5kiLCJ1c2VybmFtZSI6ImV1aWRvbmciLCJiaXJ0aERhdGUiOiIxOTk3LTA5LTI3VDAwOjAwOjAwLjAwMFoiLCJwaG9uZU51bWJlciI6IjAxMDk1Nzc0MTI3In0sImdyb3VwIjoidm1lZXRpbmciLCJ0ZW5hbnQiOiJ0cmlhbCIsInNpdGVOYW1lIjoiVHJpYWwiLCJ0diI6IjMifSwicm9vbSI6IioiLCJpYXQiOjE2NjExNTA0MDQsImV4cCI6MTY2MTc1NTIwNCwiYXVkIjoidm1lZXRpbmciLCJpc3MiOiJ2bWVldGluZ19hcHBfaWQiLCJzdWIiOiIqIn0.FyUwIwJrucIFlEtTEhL2aXTLwR3GFjFePuzP9K8zL3w";
