import _defaultUserImage from "../images/defaultUser.png";

export const defaultUserImage = _defaultUserImage;
export const DUMMY_JWT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiZW1haWwiOiJtcnJ5dTAwNkBuYXZlci5jb20iLCJpZCI6IjYzMDQyODcyODY4NzUyMDAyZjllNjBlYyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsIm5hbWUiOiLsnKDsg4HsmrAiLCJ1c2VybmFtZSI6Im1ycnl1MDA2IiwiYmlydGhEYXRlIjpudWxsLCJwaG9uZU51bWJlciI6IjAxMDAwMDAwMDAwIn0sImdyb3VwIjoidm1lZXRpbmciLCJ0ZW5hbnQiOiJ0cmlhbCIsInNpdGVOYW1lIjoiVHJpYWwiLCJ0diI6IjMifSwicm9vbSI6IioiLCJpYXQiOjE2NjI1MjQ4NjYsImV4cCI6MTY2MzEyOTY2NiwiYXVkIjoidm1lZXRpbmciLCJpc3MiOiJ2bWVldGluZ19hcHBfaWQiLCJzdWIiOiIqIn0.4M4OadRypBJi8mHYOon95sO8CiRdyi_555kmGN71uyE";
